Update failing_workflow.yaml

diff --git a/.github/workflows/failing_workflow.yaml b/.github/workflows/failing_workflow.yaml
--- a/.github/workflows/failing_workflow.yaml
+++ b/.github/workflows/failing_workflow.yaml
@@ -10,11 +10,18 @@ jobs:
     - name: Build app
       run: echo Building...  
   deploy:
+    outputs:
+      server_error: ${{ steps.deployment.outputs.server_error }}
+      app_error: ${{ steps.deployment.outputs.app_error }}
     runs-on: ubuntu-latest
     needs: [build]
     steps:
     - name: Deploy app
-      run: echo Deploying app... && exit 1
+      id: deployment
+      run: |
+        echo Deploying app...
+        >&2 echo "error" && echo "server_error=1" >> "$GITHUB_OUTPUT"
+        exit 1
   run_python_if_prev_job_failed:
     needs: [deploy]
     if: ${{ failure() }}
